security:
    firewalls:
        main:
            anonymous: ~
            guard:
                provider: cas
                authenticators:
                    - cas.guardauthenticator

    access_control:
        - { path: ^/api, role: ROLE_CAS_AUTHENTICATED }
