-- MySQL Script generated by MySQL Workbench
-- mer. 10 févr. 2021 19:43:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema data_cy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema data_cy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `data_cy` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `data_cy` ;

-- -----------------------------------------------------
-- Table `data_cy`.`Competences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`Competences` (
  `blocs` VARCHAR(45) NOT NULL,
  `seuilBlocs` VARCHAR(45) NULL DEFAULT NULL,
  `ECT` VARCHAR(45) NULL DEFAULT NULL,
  `COEFF` VARCHAR(45) NULL DEFAULT NULL,
  `seuil` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`blocs`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `data_cy`.`Cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`Cours` (
  `idCours` INT NOT NULL,
  `libelleCours` VARCHAR(45) NULL DEFAULT NULL,
  `codeAPOGEE` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCours`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `data_cy`.`Type_Controle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`Type_Controle` (
  `idType_Controle` INT NOT NULL,
  PRIMARY KEY (`idType_Controle`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `data_cy`.`UE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`UE` (
  `idUE` INT NOT NULL,
  `libelleUE` VARCHAR(45) NULL DEFAULT NULL,
  `Cours_idCours` INT NOT NULL,
  PRIMARY KEY (`idUE`, `Cours_idCours`),
  INDEX `fk_UE_Cours1_idx` (`Cours_idCours` ASC) VISIBLE,
  CONSTRAINT `fk_UE_Cours1`
    FOREIGN KEY (`Cours_idCours`)
    REFERENCES `data_cy`.`Cours` (`idCours`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `data_cy`.`MCC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`MCC` (
  `idMCC` INT NOT NULL,
  `departement` VARCHAR(45) NULL DEFAULT NULL,
  `site` VARCHAR(45) NULL DEFAULT NULL,
  `typeDiplome` VARCHAR(45) NULL DEFAULT NULL,
  `mention` VARCHAR(45) NULL DEFAULT NULL,
  `parcours` VARCHAR(45) NULL DEFAULT NULL,
  `annee` DATE NULL DEFAULT NULL,
  `niveau` VARCHAR(45) NULL DEFAULT NULL,
  `contact` VARCHAR(45) NULL DEFAULT NULL,
  `UE_idUE` INT NOT NULL,
  `Type_Controle_idType_Controle` INT NOT NULL,
  PRIMARY KEY (`idMCC`, `UE_idUE`, `Type_Controle_idType_Controle`),
  INDEX `fk_MCC_UE1_idx` (`UE_idUE` ASC) VISIBLE,
  INDEX `fk_MCC_Type_Controle1_idx` (`Type_Controle_idType_Controle` ASC) VISIBLE,
  CONSTRAINT `fk_MCC_Type_Controle1`
    FOREIGN KEY (`Type_Controle_idType_Controle`)
    REFERENCES `data_cy`.`Type_Controle` (`idType_Controle`),
  CONSTRAINT `fk_MCC_UE1`
    FOREIGN KEY (`UE_idUE`)
    REFERENCES `data_cy`.`UE` (`idUE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `data_cy`.`Semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`Semestre` (
  `idSemestre` INT NOT NULL,
  `libelle` VARCHAR(45) NULL DEFAULT NULL,
  `codeSemestre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idSemestre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `data_cy`.`Parcours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`Parcours` (
  `idParcours` INT NOT NULL,
  `libelleParcours` VARCHAR(45) NULL DEFAULT NULL,
  `structureProlonge` TINYINT NULL DEFAULT NULL,
  `structureBasse` TINYINT(1) NULL DEFAULT NULL,
  `contact` VARCHAR(45) NULL DEFAULT NULL,
  `commentaire` VARCHAR(45) NULL DEFAULT NULL,
  `libelleParcoursApogee` VARCHAR(45) NULL,
  `dateCreation` DATETIME NULL DEFAULT NULL,
  `dateModification` DATETIME NULL DEFAULT NULL,
  `secondVET` VARCHAR(45) NULL,
  `MCC_idMCC` INT NOT NULL,
  `MCC_UE_idUE` INT NOT NULL,
  `MCC_Type_Controle_idType_Controle` INT NOT NULL,
  `Semestre_idSemestre` INT NOT NULL,
  PRIMARY KEY (`idParcours`),
  INDEX `fk_Parcours_MCC1_idx` (`MCC_idMCC` ASC, `MCC_UE_idUE` ASC, `MCC_Type_Controle_idType_Controle` ASC) VISIBLE,
  INDEX `fk_Parcours_Semestre1_idx` (`Semestre_idSemestre` ASC) VISIBLE,
  CONSTRAINT `fk_Parcours_MCC1`
    FOREIGN KEY (`MCC_idMCC` , `MCC_UE_idUE` , `MCC_Type_Controle_idType_Controle`)
    REFERENCES `data_cy`.`MCC` (`idMCC` , `UE_idUE` , `Type_Controle_idType_Controle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Parcours_Semestre1`
    FOREIGN KEY (`Semestre_idSemestre`)
    REFERENCES `data_cy`.`Semestre` (`idSemestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `data_cy`.`Localisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`Localisation` (
  `idLocalisation` INT NOT NULL,
  `adresse` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `codePostal` INT NULL,
  PRIMARY KEY (`idLocalisation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_cy`.`Composante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`Composante` (
  `idComposante` INT NOT NULL,
  `libelleInstitut` VARCHAR(45) NULL,
  PRIMARY KEY (`idComposante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_cy`.`typeDiplome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`typeDiplome` (
  `idtypeDiplome` INT NOT NULL,
  PRIMARY KEY (`idtypeDiplome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_cy`.`Formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`Formation` (
  `idFormation` INT NOT NULL,
  `mention` VARCHAR(45) NULL DEFAULT NULL,
  `structureHaute` TINYINT NULL DEFAULT NULL,
  `typeFormation` VARCHAR(45) NULL DEFAULT NULL,
  `codeDiplome` VARCHAR(45) NULL DEFAULT NULL,
  `VDI` VARCHAR(45) NULL,
  `ecoleDoctorale` VARCHAR(45) NULL DEFAULT NULL,
  `contact` VARCHAR(45) NULL DEFAULT NULL,
  `commentaire` VARCHAR(45) NULL DEFAULT NULL,
  `dateCreation` DATETIME NULL DEFAULT NULL,
  `dateModification` DATETIME NULL DEFAULT NULL,
  `Parcours_idParcours` INT NOT NULL,
  `Localisation_idLocalisation` INT NOT NULL,
  `Composante_idComposante` INT NOT NULL,
  `typeDiplome_idtypeDiplome` INT NOT NULL,
  PRIMARY KEY (`idFormation`, `typeDiplome_idtypeDiplome`),
  INDEX `fk_Formation_Parcours1_idx` (`Parcours_idParcours` ASC) VISIBLE,
  INDEX `fk_Formation_Localisation1_idx` (`Localisation_idLocalisation` ASC) VISIBLE,
  INDEX `fk_Formation_Composante1_idx` (`Composante_idComposante` ASC) VISIBLE,
  INDEX `fk_Formation_typeDiplome1_idx` (`typeDiplome_idtypeDiplome` ASC) VISIBLE,
  CONSTRAINT `fk_Formation_Parcours1`
    FOREIGN KEY (`Parcours_idParcours`)
    REFERENCES `data_cy`.`Parcours` (`idParcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formation_Localisation1`
    FOREIGN KEY (`Localisation_idLocalisation`)
    REFERENCES `data_cy`.`Localisation` (`idLocalisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formation_Composante1`
    FOREIGN KEY (`Composante_idComposante`)
    REFERENCES `data_cy`.`Composante` (`idComposante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formation_typeDiplome1`
    FOREIGN KEY (`typeDiplome_idtypeDiplome`)
    REFERENCES `data_cy`.`typeDiplome` (`idtypeDiplome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `data_cy`.`SessionUnique`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`SessionUnique` (
  `idSessionUnique` INT NOT NULL,
  `typeControle` VARCHAR(45) NULL DEFAULT NULL,
  `typeEpreuve` VARCHAR(45) NULL DEFAULT NULL,
  `regleCalcul` VARCHAR(45) NULL DEFAULT NULL,
  `session` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idSessionUnique`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `data_cy`.`SessionUnique_has_Type_Controle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`SessionUnique_has_Type_Controle` (
  `SessionUnique_idSessionUnique` INT NOT NULL,
  `Type_Controle_idType_Controle` INT NOT NULL,
  `Competences_blocs` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SessionUnique_idSessionUnique`, `Type_Controle_idType_Controle`, `Competences_blocs`),
  INDEX `fk_SessionUnique_has_Type_Controle_Type_Controle1_idx` (`Type_Controle_idType_Controle` ASC) VISIBLE,
  INDEX `fk_SessionUnique_has_Type_Controle_SessionUnique1_idx` (`SessionUnique_idSessionUnique` ASC) VISIBLE,
  INDEX `fk_SessionUnique_has_Type_Controle_Competences1_idx` (`Competences_blocs` ASC) VISIBLE,
  CONSTRAINT `fk_SessionUnique_has_Type_Controle_Competences1`
    FOREIGN KEY (`Competences_blocs`)
    REFERENCES `data_cy`.`Competences` (`blocs`),
  CONSTRAINT `fk_SessionUnique_has_Type_Controle_SessionUnique1`
    FOREIGN KEY (`SessionUnique_idSessionUnique`)
    REFERENCES `data_cy`.`SessionUnique` (`idSessionUnique`),
  CONSTRAINT `fk_SessionUnique_has_Type_Controle_Type_Controle1`
    FOREIGN KEY (`Type_Controle_idType_Controle`)
    REFERENCES `data_cy`.`Type_Controle` (`idType_Controle`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `data_cy`.`coutHETD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`coutHETD` (
  `coutCM` INT NOT NULL,
  `coutTP` VARCHAR(45) NULL DEFAULT NULL,
  `coutTD` VARCHAR(45) NULL DEFAULT NULL,
  `coutHETDcol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`coutCM`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `data_cy`.`horaireTypeCours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`horaireTypeCours` (
  `horaireCM` INT NOT NULL,
  `horaireTP` VARCHAR(45) NULL DEFAULT NULL,
  `horaireTD` VARCHAR(45) NULL DEFAULT NULL,
  `horaireAutre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`horaireCM`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `data_cy`.`nbGroupeTypeCours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`nbGroupeTypeCours` (
  `CM` INT NOT NULL,
  `TP` VARCHAR(45) NULL DEFAULT NULL,
  `TD` VARCHAR(45) NULL DEFAULT NULL,
  `autre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`CM`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `data_cy`.`nbGroupeTypeCours_has_Cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`nbGroupeTypeCours_has_Cours` (
  `nbGroupeTypeCours_CM` INT NOT NULL,
  `Cours_idCours` INT NOT NULL,
  `coutHETD_coutCM` INT NOT NULL,
  `horaireTypeCours_horaireCM` INT NOT NULL,
  PRIMARY KEY (`nbGroupeTypeCours_CM`, `Cours_idCours`, `coutHETD_coutCM`, `horaireTypeCours_horaireCM`),
  INDEX `fk_nbGroupeTypeCours_has_Cours_Cours1_idx` (`Cours_idCours` ASC) VISIBLE,
  INDEX `fk_nbGroupeTypeCours_has_Cours_nbGroupeTypeCours1_idx` (`nbGroupeTypeCours_CM` ASC) VISIBLE,
  INDEX `fk_nbGroupeTypeCours_has_Cours_coutHETD1_idx` (`coutHETD_coutCM` ASC) VISIBLE,
  INDEX `fk_nbGroupeTypeCours_has_Cours_horaireTypeCours1_idx` (`horaireTypeCours_horaireCM` ASC) VISIBLE,
  CONSTRAINT `fk_nbGroupeTypeCours_has_Cours_Cours1`
    FOREIGN KEY (`Cours_idCours`)
    REFERENCES `data_cy`.`Cours` (`idCours`),
  CONSTRAINT `fk_nbGroupeTypeCours_has_Cours_coutHETD1`
    FOREIGN KEY (`coutHETD_coutCM`)
    REFERENCES `data_cy`.`coutHETD` (`coutCM`),
  CONSTRAINT `fk_nbGroupeTypeCours_has_Cours_horaireTypeCours1`
    FOREIGN KEY (`horaireTypeCours_horaireCM`)
    REFERENCES `data_cy`.`horaireTypeCours` (`horaireCM`),
  CONSTRAINT `fk_nbGroupeTypeCours_has_Cours_nbGroupeTypeCours1`
    FOREIGN KEY (`nbGroupeTypeCours_CM`)
    REFERENCES `data_cy`.`nbGroupeTypeCours` (`CM`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `data_cy`.`DiplomeEtablissement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`DiplomeEtablissement` (
  `idDiplomeEtablissement` INT NOT NULL,
  `libelleDiplome` VARCHAR(45) NULL,
  `nbAnneeDiplome` VARCHAR(45) NULL,
  PRIMARY KEY (`idDiplomeEtablissement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_cy`.`FormationNonDiplomante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`FormationNonDiplomante` (
  `idFormationNonDiplomante` INT NOT NULL,
  `libelleCertificat` VARCHAR(45) NULL,
  `nbAnneeFormation` VARCHAR(45) NULL,
  PRIMARY KEY (`idFormationNonDiplomante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_cy`.`typeDiplome_has_DiplomeEtablissement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_cy`.`typeDiplome_has_DiplomeEtablissement` (
  `typeDiplome_idtypeDiplome` INT NOT NULL,
  `DiplomeEtablissement_idDiplomeEtablissement` INT NOT NULL,
  `FormationNonDiplomante_idFormationNonDiplomante` INT NOT NULL,
  PRIMARY KEY (`typeDiplome_idtypeDiplome`, `DiplomeEtablissement_idDiplomeEtablissement`, `FormationNonDiplomante_idFormationNonDiplomante`),
  INDEX `fk_typeDiplome_has_DiplomeEtablissement_DiplomeEtablissemen_idx` (`DiplomeEtablissement_idDiplomeEtablissement` ASC) VISIBLE,
  INDEX `fk_typeDiplome_has_DiplomeEtablissement_typeDiplome1_idx` (`typeDiplome_idtypeDiplome` ASC) VISIBLE,
  INDEX `fk_typeDiplome_has_DiplomeEtablissement_FormationNonDiploma_idx` (`FormationNonDiplomante_idFormationNonDiplomante` ASC) VISIBLE,
  CONSTRAINT `fk_typeDiplome_has_DiplomeEtablissement_typeDiplome1`
    FOREIGN KEY (`typeDiplome_idtypeDiplome`)
    REFERENCES `data_cy`.`typeDiplome` (`idtypeDiplome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_typeDiplome_has_DiplomeEtablissement_DiplomeEtablissement1`
    FOREIGN KEY (`DiplomeEtablissement_idDiplomeEtablissement`)
    REFERENCES `data_cy`.`DiplomeEtablissement` (`idDiplomeEtablissement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_typeDiplome_has_DiplomeEtablissement_FormationNonDiplomante1`
    FOREIGN KEY (`FormationNonDiplomante_idFormationNonDiplomante`)
    REFERENCES `data_cy`.`FormationNonDiplomante` (`idFormationNonDiplomante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
