<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQyLWjWt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQyLWjWt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQyLWjWt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQyLWjWt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQyLWjWt\App_KernelDevDebugContainer([
    'container.build_hash' => 'QyLWjWt',
    'container.build_id' => '3bd1dc3d',
    'container.build_time' => 1613836396,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQyLWjWt');
