<?php

namespace ContainerQyLWjWt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PQR7BzmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PQR7Bzm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PQR7Bzm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'EcPhp\\CasBundle\\Controller\\Login::__invoke' => ['privates', '.service_locator.w6C1Pik', 'get_ServiceLocator_W6C1PikService', true],
            'EcPhp\\CasBundle\\Controller\\Logout::__invoke' => ['privates', '.service_locator.lcnf8r4', 'get_ServiceLocator_Lcnf8r4Service', true],
            'EcPhp\\CasBundle\\Controller\\ProxyCallback::__invoke' => ['privates', '.service_locator.Jcjrhwd', 'get_ServiceLocator_JcjrhwdService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'EcPhp\\CasBundle\\Controller\\Login:__invoke' => ['privates', '.service_locator.w6C1Pik', 'get_ServiceLocator_W6C1PikService', true],
            'EcPhp\\CasBundle\\Controller\\Login' => ['privates', '.service_locator.w6C1Pik', 'get_ServiceLocator_W6C1PikService', true],
            'EcPhp\\CasBundle\\Controller\\Logout:__invoke' => ['privates', '.service_locator.lcnf8r4', 'get_ServiceLocator_Lcnf8r4Service', true],
            'EcPhp\\CasBundle\\Controller\\Logout' => ['privates', '.service_locator.lcnf8r4', 'get_ServiceLocator_Lcnf8r4Service', true],
            'EcPhp\\CasBundle\\Controller\\ProxyCallback:__invoke' => ['privates', '.service_locator.Jcjrhwd', 'get_ServiceLocator_JcjrhwdService', true],
            'EcPhp\\CasBundle\\Controller\\ProxyCallback' => ['privates', '.service_locator.Jcjrhwd', 'get_ServiceLocator_JcjrhwdService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'EcPhp\\CasBundle\\Controller\\Login::__invoke' => '?',
            'EcPhp\\CasBundle\\Controller\\Logout::__invoke' => '?',
            'EcPhp\\CasBundle\\Controller\\ProxyCallback::__invoke' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'EcPhp\\CasBundle\\Controller\\Login:__invoke' => '?',
            'EcPhp\\CasBundle\\Controller\\Login' => '?',
            'EcPhp\\CasBundle\\Controller\\Logout:__invoke' => '?',
            'EcPhp\\CasBundle\\Controller\\Logout' => '?',
            'EcPhp\\CasBundle\\Controller\\ProxyCallback:__invoke' => '?',
            'EcPhp\\CasBundle\\Controller\\ProxyCallback' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
