<?php

namespace Container9Zadfzb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JcjrhwdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Jcjrhwd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Jcjrhwd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'casProtocol' => ['privates', 'cas', 'getCasService', true],
            'httpFoundationFactory' => ['privates', 'Symfony\\Bridge\\PsrHttpMessage\\Factory\\HttpFoundationFactory', 'getHttpFoundationFactoryService', true],
        ], [
            'casProtocol' => '?',
            'httpFoundationFactory' => '?',
        ]);
    }
}
