<?php

namespace Container9Zadfzb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W6C1PikService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w6C1Pik' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w6C1Pik'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cas' => ['privates', 'cas', 'getCasService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'cas' => '?',
            'security' => '?',
        ]);
    }
}
