<?php

namespace Container9Zadfzb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCas_UserproviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'cas.userprovider' shared autowired service.
     *
     * @return \EcPhp\CasBundle\Security\Core\User\CasUserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ecphp/cas-bundle/src/Security/Core/User/CasUserProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ecphp/cas-bundle/src/Security/Core/User/CasUserProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/ecphp/cas-lib/src/Introspection/Contract/IntrospectorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ecphp/cas-lib/src/Introspection/Introspector.php';

        return $container->privates['cas.userprovider'] = new \EcPhp\CasBundle\Security\Core\User\CasUserProvider(($container->privates['cas.introspector'] ?? ($container->privates['cas.introspector'] = new \EcPhp\CasLib\Introspection\Introspector())));
    }
}
