<?php

namespace Container9Zadfzb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCasService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'cas' shared service.
     *
     * @return \EcPhp\CasLib\Cas
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ecphp/cas-lib/src/CasInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ecphp/cas-lib/src/Cas.php';
        include_once \dirname(__DIR__, 4).'/vendor/ecphp/cas-lib/src/Configuration/PropertiesInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ecphp/cas-bundle/src/Configuration/Symfony.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-client/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/RequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/StreamFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/UriFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-client/Psr18Client.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/ResponseFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/ServerRequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/UploadedFileFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nyholm/psr7/src/Factory/Psr17Factory.php';
        include_once \dirname(__DIR__, 4).'/vendor/ecphp/cas-lib/src/Introspection/Contract/IntrospectorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ecphp/cas-lib/src/Introspection/Introspector.php';

        $a = ($container->privates['nyholm.psr7.psr17_factory'] ?? ($container->privates['nyholm.psr7.psr17_factory'] = new \Nyholm\Psr7\Factory\Psr17Factory()));

        return $container->privates['cas'] = new \EcPhp\CasLib\Cas(($container->services['psr.request'] ?? $container->load('getPsr_RequestService')), new \EcPhp\CasBundle\Configuration\Symfony($container->parameters['cas'], ($container->services['router'] ?? $container->getRouterService())), new \Symfony\Component\HttpClient\Psr18Client(($container->privates['http_client'] ?? $container->load('getHttpClientService')), $a, $a), $a, $a, $a, $a, ($container->services['cache.app'] ?? $container->load('getCache_AppService')), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), ($container->privates['cas.introspector'] ?? ($container->privates['cas.introspector'] = new \EcPhp\CasLib\Introspection\Introspector())));
    }
}
