<?php

namespace Container9Zadfzb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogoutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'EcPhp\CasBundle\Controller\Logout' shared autowired service.
     *
     * @return \EcPhp\CasBundle\Controller\Logout
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ecphp/cas-bundle/src/Controller/Logout.php';

        return $container->services['EcPhp\\CasBundle\\Controller\\Logout'] = new \EcPhp\CasBundle\Controller\Logout();
    }
}
