<?php

namespace Container9Zadfzb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPsr_RequestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'psr.request' shared service.
     *
     * @return \Psr\Http\Message\RequestInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-message/src/MessageInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-message/src/RequestInterface.php';

        return $container->services['psr.request'] = ($container->privates['sensio_framework_extra.psr7.http_message_factory'] ?? $container->load('getSensioFrameworkExtra_Psr7_HttpMessageFactoryService'))->createRequest(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()))->getCurrentRequest());
    }
}
